const POSSIBILITIES = [
    "Coma uma fruta agora",
    "Leia um artigo técnico",
    "Escreva 3 linhas sobre seu dia",
    "Veja as notícias principais",
    "Beba 500ml de água"
];

export const generateSurpriseTask = () => {
    // Lógica: 10% de chance de aparecer se o usuário abrir o app
    // e se ele não tiver tido 4 surpresas no mês atual ainda.
    const rand = Math.random();
    if (rand < 0.1) {
        const title = POSSIBILITIES[Math.floor(Math.random() * POSSIBILITIES.length)];
        return {
            title,
            type: 'surprise',
            priority: 'P2',
            rewardMult: 2, // Recompensa de Desafio Diário
            isAutoGenerated: true
        };
    }
    return null;
};
